// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDQtUDeUzEonb-5ghJz5gaqh0-u7cZNVs',
    appId: '1:687457468654:web:1fe3087a68ee892a8c33ff',
    messagingSenderId: '687457468654',
    projectId: 'flutter-instagram-clone-44e05',
    authDomain: 'flutter-instagram-clone-44e05.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-44e05.firebasestorage.app',
    measurementId: 'G-B49CHGWXT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5TLKRZHnGv8-R3FxhIXyp-gehdixHEwE',
    appId: '1:687457468654:android:1a53e9eda1b84ae18c33ff',
    messagingSenderId: '687457468654',
    projectId: 'flutter-instagram-clone-44e05',
    storageBucket: 'flutter-instagram-clone-44e05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ghDknJgIu2lhbP34aPlOkRRAaeGUF1Q',
    appId: '1:687457468654:ios:ca556a4da90c11be8c33ff',
    messagingSenderId: '687457468654',
    projectId: 'flutter-instagram-clone-44e05',
    storageBucket: 'flutter-instagram-clone-44e05.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ghDknJgIu2lhbP34aPlOkRRAaeGUF1Q',
    appId: '1:687457468654:ios:ca556a4da90c11be8c33ff',
    messagingSenderId: '687457468654',
    projectId: 'flutter-instagram-clone-44e05',
    storageBucket: 'flutter-instagram-clone-44e05.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDQtUDeUzEonb-5ghJz5gaqh0-u7cZNVs',
    appId: '1:687457468654:web:a058410bddb6db818c33ff',
    messagingSenderId: '687457468654',
    projectId: 'flutter-instagram-clone-44e05',
    authDomain: 'flutter-instagram-clone-44e05.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-44e05.firebasestorage.app',
    measurementId: 'G-0GKFSH0JRN',
  );

}